"use client";

import React, { useRef, useState } from "react";
import Link from "next/link";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { 
  ArrowDownRight, 
  ArrowRight,
  Crosshair,
  Bug,
  Terminal,
  ShieldAlert,
  Fingerprint,
  Wifi,
  Users,
  DatabaseZap,
  LockKeyhole,
  SearchCode,
  FileCheck2,
  TerminalSquare
} from "lucide-react";

gsap.registerPlugin(useGSAP, ScrollTrigger);

// ==========================================
// 1. PEN-TEST HERO SECTION
// ==========================================
function PenTestHero() {
  const container = useRef<HTMLElement>(null);

  useGSAP(() => {
    const tl = gsap.timeline({ defaults: { ease: "expo.out" } });

    tl.fromTo(
        ".hero-word", 
        { opacity: 0, y: 50, rotateX: -20 }, 
        { opacity: 1, y: 0, rotateX: 0, duration: 1.2, stagger: 0.1 }, 
        "+=0.1"
      )
      .fromTo(
        ".hero-desc", 
        { opacity: 0, y: 20 }, 
        { opacity: 1, y: 0, duration: 1 }, 
        "-=0.8"
      );
  }, { scope: container });

  return (
    <section ref={container} className="relative bg-[#FAFAFA] pt-24 sm:pt-48 pb-20 font-sans overflow-hidden border-b border-slate-200">
      
      {/* Massive Faint Crosshair Watermark */}
      <div className="absolute top-1/2 right-0 -translate-y-1/2 translate-x-1/4 opacity-[0.03] pointer-events-none text-rose-900">
        <Crosshair strokeWidth={1} className="w-[600px] h-[600px] sm:w-[800px] sm:h-[800px]" />
      </div>

      <div className="absolute inset-0 pointer-events-none opacity-[0.03]">
        <div className="absolute top-1/4 left-1/4 w-[40rem] h-[40rem] rounded-full bg-rose-600 blur-[120px]"></div>
        <div className="absolute bottom-1/4 right-1/4 w-[30rem] h-[30rem] rounded-full bg-slate-900 blur-[100px]"></div>
      </div>

      <div className="relative z-10 mx-auto max-w-7xl px-6 lg:px-8">
        <div className="max-w-4xl">
          
          <h1 className="font-heading text-5xl sm:text-7xl lg:text-[5.5rem] font-black tracking-tighter text-slate-900 leading-[1.05] mb-8 flex flex-wrap gap-x-4 gap-y-2 perspective-1000">
            <span className="hero-word overflow-hidden">Simulated</span>
            <span className="hero-word overflow-hidden text-slate-400">attacks.</span>
            <span className="hero-word overflow-hidden">Absolute</span>
            <span className="hero-word overflow-hidden font-serif italic font-medium text-rose-600 pr-2">defense.</span>
          </h1>

          <p className="hero-desc text-lg sm:text-xl text-slate-600 font-medium leading-relaxed max-w-2xl mb-12">
            Automated tools find bugs. We find breaches. Our elite Red Team executes military-grade adversarial simulations to exploit your networks, applications, and human layer before real threat actors do.
          </p>

          <div className="hero-desc flex items-center gap-4">
            <Link href="#kill-chain" className="rounded-xl bg-rose-600 px-8 py-3.5 text-sm font-bold text-white shadow-sm transition-all hover:bg-rose-700 hover:shadow-lg hover:shadow-rose-600/20 active:scale-95">
              Review Methodology
            </Link>
          </div>

        </div>
      </div>
    </section>
  );
}

// ==========================================
// 2. THE REALITY CHECK
// ==========================================
function PenTestContext() {
  const container = useRef<HTMLElement>(null);

  useGSAP(() => {
    gsap.fromTo(".ctx-fade", 
      { opacity: 0, y: 30 }, 
      { opacity: 1, y: 0, duration: 1, stagger: 0.15, ease: "power3.out", scrollTrigger: { trigger: container.current, start: "top 75%" } }
    );
  }, { scope: container });

  return (
    <section ref={container} className="bg-white py-24 sm:py-32 font-sans border-b border-slate-100">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24 items-center">
          
          <div className="relative">
            <ArrowDownRight className="ctx-fade h-8 w-8 text-rose-600 mb-8" strokeWidth={1.5} />
            <h2 className="ctx-fade font-heading text-4xl sm:text-5xl font-black text-slate-900 tracking-tight leading-[1.1] mb-6">
              A vulnerability scan is <span className="text-slate-400">not</span> a <span className="font-serif italic font-medium text-slate-500">penetration test.</span>
            </h2>
            <p className="ctx-fade text-lg text-slate-500 font-medium leading-relaxed mb-8">
              Paying thousands of dollars for a PDF generated by an automated SaaS scanner is a waste of capital. Hackers don't follow checklists. They chain low-level vulnerabilities together to execute catastrophic breaches.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            {[
              { title: "Business Logic Flaws", desc: "Scanners miss price manipulation, privilege escalation, and workflow bypasses. We find them manually." },
              { title: "Exploit Chaining", desc: "A minor XSS bug combined with an exposed admin endpoint creates a full system takeover." },
              { title: "Zero False Positives", desc: "We don't hand you theoretical warnings. Every vulnerability we report has been actively verified." },
              { title: "The Human Element", desc: "Phishing and social engineering bypass the best firewalls. We test your team's operational security." }
            ].map((item, i) => (
              <div key={i} className="ctx-fade p-8 rounded-3xl bg-[#FAFAFA] border border-slate-200 shadow-sm transition-shadow hover:shadow-md hover:border-rose-100">
                <div className="text-[10px] font-bold uppercase tracking-widest text-rose-600 mb-4">0{i + 1}</div>
                <h3 className="font-heading text-lg font-bold text-slate-900 mb-2">{item.title}</h3>
                <p className="text-xs text-slate-500 font-medium leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>

        </div>
      </div>
    </section>
  );
}

// ==========================================
// 3. THE FORENSIC CODE INSPECTOR
// ==========================================
export function ForensicCodeInspector() {
    const container = useRef<HTMLElement>(null);
  
    useGSAP(() => {
      const panels = gsap.utils.toArray(".fi-text-panel");
      const codeBlocks = gsap.utils.toArray(".fi-code-block");
  
      // Pin the right side code window while the left side scrolls
      ScrollTrigger.create({
        trigger: container.current,
        start: "top top",
        end: "bottom bottom",
        pin: ".fi-code-container",
      });
  
      // Link each text panel to its corresponding code block
      panels.forEach((panel: any, i) => {
        ScrollTrigger.create({
          trigger: panel,
          start: "top center",
          end: "bottom center",
          onEnter: () => activateCode(i),
          onEnterBack: () => activateCode(i),
        });
      });
  
      function activateCode(index: number) {
        codeBlocks.forEach((block: any, i) => {
          gsap.to(block, {
            opacity: i === index ? 1 : 0,
            y: i === index ? 0 : 20,
            duration: 0.5,
            pointerEvents: i === index ? "auto" : "none",
          });
        });
      }
    }, { scope: container });
  
    const AUDIT_SCENARIOS = [
      {
        title: "Broken Authentication",
        desc: "Standard scanners check if JWTs are present. We check if the signature is actually verified. A common fatal flaw allows attackers to forge administrative tokens by changing the encryption algorithm.",
        code: `// VULNERABLE IMPLEMENTATION
  function verifyToken(token) {
    // FAULT: Does not enforce algorithm type
    const decoded = jwt.decode(token, { complete: true });
    if (decoded.header.alg === 'none') {
      return decoded.payload; // CRITICAL BYPASS
    }
    return jwt.verify(token, SECRET_KEY);
  }`
      },
      {
        title: "Business Logic Manipulation",
        desc: "Can a user buy a $1,000 item by manipulating the API payload to send a negative quantity? Automated tools can't understand business context. Our architects can.",
        code: `// VULNERABLE IMPLEMENTATION
  app.post('/api/checkout', (req, res) => {
    const { cartItems } = req.body;
    let total = 0;
    
    cartItems.forEach(item => {
      // FAULT: No validation on negative quantities
      total += (item.price * item.quantity); 
    });
    
    chargeUser(req.user, total);
  });`
      },
      {
        title: "Insecure Direct Object Reference (IDOR)",
        desc: "Just because an endpoint requires a login doesn't mean it's secure. We test if a standard user can access another user's private data simply by iterating URL parameters.",
        code: `// VULNERABLE IMPLEMENTATION
  app.get('/api/users/:id/invoices', (req, res) => {
    const invoiceId = req.params.id;
    
    // FAULT: Checks if user is logged in, 
    // but NOT if they own this specific invoice.
    if (!req.session.isAuthenticated) return reject();
    
    const data = db.invoices.find(invoiceId);
    return res.json(data); // MASS DATA EXFILTRATION
  });`
      }
    ];
  
    return (
      <section ref={container} className="relative bg-slate-950 font-sans border-b border-slate-900">
        
        <div className="mx-auto max-w-7xl px-6 lg:px-8 grid grid-cols-1 lg:grid-cols-2 gap-16">
          
          {/* LEFT: Scrolling Text Panels */}
          <div className="py-[30vh]">
            {AUDIT_SCENARIOS.map((scenario, idx) => (
              <div key={idx} className="fi-text-panel min-h-[70vh] flex flex-col justify-center pr-8">
                <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-red-500/10 border border-red-500/20 text-red-500 mb-6 font-mono font-bold text-sm">
                  0{idx + 1}
                </div>
                <h3 className="font-heading text-3xl sm:text-4xl font-black text-white tracking-tight mb-6">
                  {scenario.title}
                </h3>
                <p className="text-lg text-slate-400 font-medium leading-relaxed">
                  {scenario.desc}
                </p>
              </div>
            ))}
          </div>
  
          {/* RIGHT: Pinned Code Editor */}
          <div className="fi-code-container h-screen flex flex-col justify-center hidden lg:flex">
            <div className="w-full h-[500px] rounded-2xl bg-[#0B1120] border border-slate-800 shadow-2xl overflow-hidden flex flex-col relative">
              
              {/* Mock Header */}
              <div className="h-12 border-b border-slate-800/60 bg-[#0F172A] flex items-center px-4 gap-2">
                <div className="h-3 w-3 rounded-full bg-red-500/20 border border-red-500/50"></div>
                <div className="h-3 w-3 rounded-full bg-amber-500/20 border border-amber-500/50"></div>
                <div className="h-3 w-3 rounded-full bg-emerald-500/20 border border-emerald-500/50"></div>
                <div className="ml-4 flex items-center gap-2 px-3 py-1 bg-slate-900 rounded-md border border-slate-800 text-[10px] font-mono text-slate-500">
                  <SearchCode className="h-3 w-3" /> vulnerability_scan.js
                </div>
              </div>
  
              {/* Code Body */}
              <div className="relative flex-1 p-6 bg-[#020617] font-mono text-sm leading-relaxed overflow-hidden">
                {AUDIT_SCENARIOS.map((scenario, idx) => (
                  <div key={idx} className="fi-code-block absolute inset-0 p-6 opacity-0">
                    <pre className="text-slate-300 whitespace-pre-wrap">
                      <code dangerouslySetInnerHTML={{ 
                        __html: scenario.code
                          .replace(/\/\/.*/g, match => `<span class="text-slate-500">${match}</span>`)
                          .replace(/function|const|let|return|if/g, match => `<span class="text-blue-400">${match}</span>`)
                          .replace(/FAULTS?:.*/g, match => `<span class="text-red-400 bg-red-500/10 px-1 rounded">${match}</span>`)
                          .replace(/CRITICAL BYPASS|MASS DATA EXFILTRATION/g, match => `<span class="text-white bg-red-600 px-1 rounded animate-pulse">${match}</span>`)
                      }} />
                    </pre>
                  </div>
                ))}
              </div>
  
            </div>
          </div>
  
        </div>
      </section>
    );
  }

  // ==========================================
// 4. THE METHODOLOGY STACK
// ==========================================
export function MethodologyStack() {
    const container = useRef<HTMLElement>(null);
  
    useGSAP(() => {
      const cards = gsap.utils.toArray<HTMLElement>(".stack-card");
      const STACK_HEIGHT = window.innerHeight;
  
      const tl = gsap.timeline({
        scrollTrigger: {
          trigger: container.current,
          start: "top top",
          end: `+=${STACK_HEIGHT * 3}`, // 3 transitions
          scrub: 1,
          pin: true,
        }
      });
  
      cards.forEach((card: any, i) => {
        if (i === 0) return; // First card is already in position
  
        // Slide the new card up from the bottom
        tl.fromTo(card, 
          { y: "100%", boxShadow: "0 -20px 40px rgba(0,0,0,0)" }, 
          { y: "0%", boxShadow: "0 -20px 40px rgba(0,0,0,0.1)", ease: "none" }
        );
  
        // Scale down and darken the PREVIOUS cards to create depth
        for (let j = 0; j < i; j++) {
          tl.to(cards[j], {
            scale: 1 - (i - j) * 0.05,
            y: -(i - j) * 20,
            filter: `brightness(${1 - (i - j) * 0.1})`,
            ease: "none"
          }, "<");
        }
      });
    }, { scope: container });
  
    const PHASES = [
      { num: "Phase I", title: "Rules of Engagement", desc: "We define the exact scope, off-limit targets, and testing windows. We establish secure communication channels to ensure zero disruption to your active business operations.", color: "bg-white" },
      { num: "Phase II", title: "OSINT & Reconnaissance", desc: "Our team maps your external attack surface. We scour GitHub for leaked credentials, enumerate subdomains, and identify shadow IT assets your team forgot about.", color: "bg-slate-50" },
      { num: "Phase III", title: "Weaponization & Exploitation", desc: "We deploy custom payloads and manual exploitation techniques to breach your perimeter, bypass WAFs, and gain initial access into your infrastructure.", color: "bg-red-50" },
      { num: "Phase IV", title: "Lateral Movement & Exfil", desc: "Once inside, we attempt to escalate privileges and access sensitive databases, proving the exact blast radius of a successful breach.", color: "bg-red-600 text-white" }
    ];
  
    return (
      <section ref={container} className="relative h-screen bg-[#FAFAFA] font-sans overflow-hidden border-b border-slate-200">
        
        {/* Background Title */}
        <div className="absolute top-12 left-0 w-full text-center px-6 pointer-events-none">
          <p className="text-xs font-bold uppercase tracking-widest text-red-600 mb-2">The Protocol</p>
          <h2 className="font-heading text-4xl sm:text-5xl font-black text-slate-900 tracking-tight">Clinical Execution.</h2>
        </div>
  
        <div className="relative w-full max-w-4xl mx-auto h-full flex items-end sm:items-center justify-center pt-32 pb-12 sm:pb-0 px-6">
          
          <div className="relative w-full h-[60vh] sm:h-[500px]">
            {PHASES.map((phase, idx) => (
              <div 
                key={idx} 
                className={`stack-card absolute top-0 left-0 w-full h-full rounded-[2rem] sm:rounded-[3rem] border border-slate-200/50 p-8 sm:p-16 flex flex-col justify-center shadow-lg will-change-transform ${phase.color}`}
                style={{ zIndex: idx }}
              >
                <div className="max-w-xl">
                  <span className={`inline-block px-4 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-widest mb-6 ${idx === 3 ? "bg-white/20 text-white" : "bg-slate-200 text-slate-600"}`}>
                    {phase.num}
                  </span>
                  <h3 className={`font-heading text-4xl sm:text-5xl font-black tracking-tight mb-6 ${idx === 3 ? "text-white" : "text-slate-900"}`}>
                    {phase.title}
                  </h3>
                  <p className={`text-lg sm:text-xl font-medium leading-relaxed ${idx === 3 ? "text-red-100" : "text-slate-500"}`}>
                    {phase.desc}
                  </p>
                </div>
              </div>
            ))}
          </div>
  
        </div>
      </section>
    );
  }

  // ==========================================


export function DeliverablesShowcase() {
  const [activeIndex, setActiveIndex] = useState(0);

  const DELIVERABLES = [
    {
      title: "The Executive Brief",
      desc: "Translates critical technical risk into business impact and financial exposure for the C-Suite and Board of Directors.",
      icon: <FileCheck2 className="h-6 w-6" />,
      visual: (
        <div className="w-full h-full bg-slate-50 p-6 flex flex-col gap-4">
          <div className="h-8 w-1/3 bg-slate-200 rounded"></div>
          <div className="flex gap-4 mb-4">
            <div className="h-24 flex-1 bg-red-500/10 border border-red-500/20 rounded-xl flex items-center justify-center text-red-600 font-bold text-2xl">High Risk</div>
            <div className="h-24 flex-1 bg-white border border-slate-200 rounded-xl"></div>
          </div>
          <div className="h-4 w-full bg-slate-200 rounded"></div>
          <div className="h-4 w-5/6 bg-slate-200 rounded"></div>
        </div>
      )
    },
    {
      title: "Remediation Blueprint",
      desc: "Deeply technical, line-by-line code patches and architectural restructuring guidelines for your engineering team.",
      icon: <SearchCode className="h-6 w-6" />,
      visual: (
        <div className="w-full h-full bg-[#0F172A] p-6 flex flex-col gap-3 font-mono text-xs">
          <div className="text-red-400">- const query = `SELECT * FROM users WHERE id = \$1`;</div>
          <div className="text-emerald-400 mb-4">+ const query = 'SELECT * FROM users WHERE id = $1';</div>
          <div className="h-px w-full bg-slate-800 my-2"></div>
          <div className="text-slate-400">// Recommendation: Implement Parameterized Queries</div>
        </div>
      )
    },
    {
      title: "CI/CD DevSecOps Integration",
      desc: "We help integrate automated security gating directly into your GitHub Actions, blocking bad code before it merges.",
      icon: <TerminalSquare className="h-6 w-6" />,
      visual: (
        <div className="w-full h-full bg-slate-100 p-6 flex items-center justify-center">
          <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-md flex items-center gap-4 w-full max-w-sm">
            <div className="h-10 w-10 rounded-full bg-red-100 flex items-center justify-center text-red-600"><ShieldAlert className="h-5 w-5"/></div>
            <div>
              <p className="text-sm font-bold text-slate-900">Merge Blocked</p>
              <p className="text-xs text-slate-500">Bitmos SAST found 1 Critical Flaw.</p>
            </div>
          </div>
        </div>
      )
    }
  ];

  return (
    <section className="bg-white py-24 sm:py-32 font-sans border-b border-slate-100">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        
        <div className="mb-16 md:mb-24 text-center max-w-3xl mx-auto">
          <h2 className="font-heading text-4xl sm:text-5xl font-black text-slate-900 tracking-tight leading-[1.05] mb-6">
            Actionable <span className="text-slate-400">Intelligence.</span>
          </h2>
          <p className="text-lg text-slate-500 font-medium leading-relaxed">
            We don't hand you a 200-page PDF generated by a bot. You receive prioritized, highly technical roadmaps that your engineering team can start executing immediately.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-24 items-center">
          
          {/* LEFT: Interaction List */}
          <div className="flex flex-col gap-4">
            {DELIVERABLES.map((item, idx) => (
              <div 
                key={idx}
                onMouseEnter={() => setActiveIndex(idx)}
                className={`cursor-pointer p-6 sm:p-8 rounded-3xl border transition-all duration-300 ${
                  activeIndex === idx 
                  ? "bg-slate-50 border-slate-200 shadow-md scale-[1.02]" 
                  : "bg-white border-transparent hover:bg-slate-50/50"
                }`}
              >
                <div className={`flex h-12 w-12 items-center justify-center rounded-xl mb-4 transition-colors ${activeIndex === idx ? "bg-red-50 text-red-600" : "bg-slate-100 text-slate-400"}`}>
                  {item.icon}
                </div>
                <h3 className={`font-heading text-2xl font-bold mb-2 transition-colors ${activeIndex === idx ? "text-slate-900" : "text-slate-600"}`}>
                  {item.title}
                </h3>
                <p className="text-sm text-slate-500 font-medium leading-relaxed">
                  {item.desc}
                </p>
              </div>
            ))}
          </div>

          {/* RIGHT: Dynamic Visual Frame */}
          <div className="h-[400px] sm:h-[500px] rounded-[2.5rem] bg-white border border-slate-200 shadow-2xl p-4 overflow-hidden relative">
            <div className="w-full h-full rounded-[1.5rem] overflow-hidden border border-slate-100 relative">
              {DELIVERABLES.map((item, idx) => (
                <div 
                  key={idx} 
                  className={`absolute inset-0 transition-opacity duration-500 ease-in-out ${activeIndex === idx ? "opacity-100 z-10" : "opacity-0 z-0"}`}
                >
                  {item.visual}
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </section>
  );
}
// ==========================================
// MAIN EXPORT
// ==========================================
export default function PenTestingPage() {
  return (
    <main className="w-full">
      <PenTestHero />
      <PenTestContext />
      <ForensicCodeInspector />
      <MethodologyStack />
      <DeliverablesShowcase />
    </main>
  );
}